# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRjz9QRyeJyesExUidIa77X7tiJ78yvO
"""

!pip install streamlit
!pip install joblib

# streamlit_app/app.py

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load model
model = joblib.load("post_recommender_model.pkl")
model_features = model.feature_name_

st.title("Post Engagement Recommender")
st.write("Suggest a new post idea and see its predicted engagement!")

# === User Inputs ===
st.subheader("Post Idea Inputs")

caption_length_words = st.slider("Caption Length (words)", 5, 100, 20)
caption_length_chars = st.slider("Caption Length (characters)", 20, 500, 120)
month = st.selectbox("Month", list(range(1, 13)))
hour = st.slider("Hour of Day Posted", 0, 23, 10)
clicks = st.slider("Expected Clicks", 0, 100, 20)
impressions = st.slider("Expected Impressions", 500, 10000, 2000)
ctr = (clicks / impressions) * 100
engagement_rate = st.slider("Expected Engagement Rate (%)", 0.0, 10.0, 3.0)

post_type = st.selectbox("Post Type", ["video", "text", "image"])
day_of_week = st.selectbox("Day of Week", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])

# Convert to feature format
input_dict = {
    "caption_length_words": caption_length_words,
    "caption_length_chars": caption_length_chars,
    "month": month,
    "hour": hour,
    "clicks": clicks,
    "impressions": impressions,
    "click_through_rate_(ctr)": ctr,
    "engagement_rate": engagement_rate,
}

# One-hot encode post_type
for pt in ["video", "text", "image"]:
    input_dict[f"post_type_{pt}"] = 1 if post_type == pt else 0

# One-hot encode day_of_week
for dow in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]:
    input_dict[f"day_of_week_{dow}"] = 1 if day_of_week == dow else 0

# Convert to DataFrame
input_df = pd.DataFrame([input_dict])
input_df = input_df[model_features]  # align with training features

# Predict
if st.button("Predict Engagement"):
    prediction = model.predict(input_df)[0]
    st.success(f"Predicted Engagement: **{round(prediction, 2)}**")